#轉大寫 & 去除所有Corporation及Limited Liability Company 型態

TAKE_OUT_CORP_LLC_LTD =['COMPANY',
 'INCORPORATED','CORPORATION','CORP.','CORP','INC',
 'INC.','S.P.A.','N.V.','A.G.','AG','NUF','S.A.',
 'S.F.','OAO','CO.','CO','KABUSHIKI','KAISHA','KABUSHIKIKAISHA',
 'KK','K.K.','K.K','KABUSHIKI-KAISHA','PLLC','LLC','L.L.C.','PLC.','PLC',
 'HF.','OYJ','A.E.','NYRT.','P.L.C.','SH.A.','S.A.',
 'S.R.L.','SRL.','SRL','AAT','3AT','D.D.','S.R.O.',
 'SPOL. S R.O.','S.M.B.A.','SMBA','SARL','NV','SA',
 'APS','A/S','P/S','SAE','SASU','EURL','AE','CPT',
 'AS','AB','ASA','OOO','DAT','VAT', 'ZAT','MCHJ',
 'A.D.','PTY. LTD.','PTY LTD','LTD',
 'L.T.D.','LTD.','BVBA','D.O.O.','LTDA',
 'GMBH','G.M.B.H','KFT.','KHT.','ZRT.','EHF.',
 'S.A.R.L.','D.O.O.E.L.','S. DE R.L.',
 'B.V.','TAPUI','SP. Z.O.O.','SP. Z O.O.',
 'S.R.L.','S.L.','S.L.N.E.','OOD','OY',
 'RT.','TEO','UAB','SCS','SPRL',
 'LIMITED','BHD.','SDN. BHD.',
 'SDN BHD','AS','LDA.', 'TOV',
 'PP','THE','AND','OF']

TAKE_OUT_CORP_LLC_LTD_GERMANY =['COMPANY',
 'INCORPORATED','CORPORATION','CORP.','CORP','INC',
 'INC.','S.P.A.','N.V.','A.G.','AG','NUF','S.A.',
 'S.F.','OAO','CO.','CO','KABUSHIKI','KAISHA','KK','KABUSHIKIKAISHA',
 'K.K.','K.K','PLLC','LLC','L.L.C.','PLC.','PLC',
 'HF.','OYJ','A.E.','NYRT.','P.L.C.','SH.A.','S.A.',
 'S.R.L.','SRL.','SRL','AAT','3AT','D.D.','S.R.O.',
 'SPOL. S R.O.','S.M.B.A.','SMBA','SARL','NV','SA',
 'APS','A/S','P/S','SAE','SASU','EURL','AE','CPT',
 'AS','AB','ASA','OOO','DAT','VAT', 'ZAT','MCHJ',
 'A.D.','PTY. LTD.','PTY LTD','LTD',
 'L.T.D.','LTD.','BVBA','D.O.O.','LTDA',
 'GMBH','G.M.B.H','KFT.','KHT.','ZRT.','EHF.',
 'S.A.R.L.','D.O.O.E.L.','S. DE R.L.',
 'B.V.','TAPUI','SP. Z.O.O.','SP. Z O.O.',
 'S.R.L.','S.L.','S.L.N.E.','OOD','OY',
 'RT.','TEO','UAB','SCS','SPRL',
 'LIMITED','BHD.','SDN. BHD.',
 'SDN BHD','AS','LDA.', 'TOV',
 'PP','THE','AND','OF','E.G.',
 'E.V.','GBR','OHG','PARTG',
 'KGAA','GMBH','G.M.B.H.','AG','KG'
]

WRONG_WORDS_CROP=['COPORATION','COROPORATION','CORPORAION','CORPORATI','CORPORATIION',
 'CORPORATON','CORPORTAION','CORPORTION','CORPOTRATION','CORPROATION','CORP'
]
WRONG_WORDS_INC=['INCOPORATION','INCOROPORATION','INCORPORAION','INCORPORATI','INCORPORATIION',
 'INCORPORATON','INCORPORTAION','INCORPORTION','INCORPOTRATION','INCORPROATION','INCORPORATION'
]
WRONG_WORDS_CO=['COMANY', 'COMAPNY', 'COMPAMY']

WRONG_WORDS_KK=['KABUSHIKIKAISYA','KAISYA', 'KAIGHA','KAISHI','DABUSHIKI','KAISAHA','KAUBSHIKI']

WRONG_WORDS_GMBH=['GBMH']

OTHERS=['&AMP;','&']


def WRONG_WORDS_ALL():
    WRONG_WORDS_ALL=[]
    WRONG_WORDS_ALL.append(WRONG_WORDS_CROP)
    WRONG_WORDS_ALL.append(WRONG_WORDS_INC)
    WRONG_WORDS_ALL.append(WRONG_WORDS_CO)
    WRONG_WORDS_ALL.append(WRONG_WORDS_KK)
    WRONG_WORDS_ALL.append(WRONG_WORDS_GMBH)
    WRONG_WORDS_ALL.append(OTHERS)